-- CREATE TABLE IF NOT EXISTS Media (
--     media_id INT NOT NULL,
--     user_id INT NOT NULL,
--     filename VARCHAR(255) NOT NULL,
--     filesize INT NOT NULL,
--     media_type VARCHAR(255) NOT NULL,
--     title VARCHAR(255) NOT NULL,
--     description VARCHAR(255),
--     created_at TIMESTAMP NOT NULL
-- --     PRIMARY KEY (media_id),
-- );